version: '3.1'
services:
    postgres:
        build: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432

    youless:
        build: .
        working_dir: /app/
        volumes:
           - ./youless/:/app/
        environment:
           - 'CRON_STRINGS=* * * * * python3 /app/poll.py'
        links:
           - postgres:postgres

    apx:
        build: .
        working_dir: /app/
        environment:
            - 'CRON_STRINGS=0 * * * * python3 /app/poll.py'
        volumes:
            - ./apx/:/app/
        links:
            - postgres:postgres

    energyzero:
        build: .
        links:
            - postgres:postgres
        environment:
            - 'TOKEN=...'

    metabase:
        image: metabase/metabase:latest
        ports:
            - 3000:3000
        links:
            - postgres:postgres
        environment:
            - MB_DB_TYPE=postgres
            - MB_DB_DBNAME=metabase
            - MB_DB_PORT=5432
            - MB_DB_USER=postgres
            - MB_DB_PASS=postgres
            - MB_DB_HOST=postgres
