version: '3.1'
services:
    postgres:
        build: postgres
        environment:
            - POSTGRES_USER=fokko
            - POSTGRES_PASSWORD=fokko
            - POSTGRES_DB=fokko
        ports:
            - 5432:5432

    youless:
        build: youless
        working_dir: /app/
        volumes:
           - ./youless/:/app/
        environment:
           - 'CRON_STRINGS=* * * * * python3 /app/poll.py'
        links:
           - postgres:postgres

    tesla:
        build: tesla
        working_dir: /app/
        volumes:
           - ./tesla/:/app/
        environment:
           - 'CRON_STRINGS=*/5 * * * * python3 /app/poll.py'
           - TESLA_EMAIL
           - TESLA_PASSWORD
        links:
           - postgres:postgres

    apx:
        build: apx
        working_dir: /app/
        environment:
            - 'CRON_STRINGS=0 * * * * python3 /app/poll.py'
        volumes:
            - ./apx/:/app/
        links:
            - postgres:postgres

    energyzero:
        build: energyzero
        links:
            - postgres:postgres
        environment:
            - 'TOKEN=...'

    otgw:
        build: otgw
        working_dir: /app/
        tty: true
        volumes:
            - ./otgw/:/app/
        links:
            - postgres:postgres

    charge-bot:
        build: charge_bot
        working_dir: /app/
        volumes:
            - ./charge_bot/:/app/
        links:
            - postgres:postgres
        environment:
            - TELEGRAM_TOKEN
        depends_on:
            - tesla
            - apx

    metabase:
        image: metabase/metabase:latest
        ports:
            - 3000:3000
        links:
            - postgres:postgres
        environment:
            - MB_DB_TYPE=postgres
            - MB_DB_DBNAME=metabase
            - MB_DB_PORT=5432
            - MB_DB_USER=fokko
            - MB_DB_PASS=fokko
            - MB_DB_HOST=postgres
