CREATE TABLE IF NOT EXISTS relay_state (
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP PRIMARY KEY,
  A          DOUBLE PRECISION NOT NULL,
  B          DOUBLE PRECISION NOT NULL
)
